// Package affiliate defines the domain types for the referral and affiliate
// earnings system in the prediction market platform service.
package affiliate

import (
	"errors"
	"time"
)

// Sentinel errors for the affiliate domain.
var (
	ErrNotFound          = errors.New("not found")
	ErrDuplicateReferral = errors.New("duplicate referral")
	ErrSelfReferral      = errors.New("self referral")
	ErrCircularReferral  = errors.New("circular referral")
	ErrDuplicateEarning  = errors.New("duplicate earning")
	ErrInvalidReferral   = errors.New("invalid referral")
)

// Referral represents a referrer-referred relationship between two users.
type Referral struct {
	ReferrerAddress string // Ethereum address of the referrer.
	ReferredAddress string // Ethereum address of the referred user.
	CreatedAt       time.Time
}

// Earning represents a single earning event from a referred user's trade.
// All monetary amounts are in integer cents (1 = $0.01).
type Earning struct {
	ID              string // UUID, generated by database.
	ReferrerAddress string // Ethereum address of the earning referrer.
	TradeID         string // FK to trades; idempotency key.
	FeeAmount       int64  // Total fee from the trade, in cents.
	ReferrerCut     int64  // Portion of fee credited to referrer, in cents.
	CreatedAt       time.Time
}

// ClaimableBalance represents a referrer's aggregate earnings.
// All monetary amounts are in integer cents (1 = $0.01).
type ClaimableBalance struct {
	ReferrerAddress string
	TotalEarned     int64 // Sum of all referrer_cut values.
	Claimable       int64 // Available to claim (equal to TotalEarned for now).
}
