// Package market defines the core domain types for the prediction market
// platform service: events, markets, categories, and their associated enumerations.
package market

import (
	"encoding/json"
	"errors"
	"time"
)

// Sentinel errors for the market domain.
var (
	ErrNotFound          = errors.New("not found")
	ErrInvalidEvent      = errors.New("invalid event")
	ErrInvalidMarket     = errors.New("invalid market")
	ErrInvalidTransition = errors.New("invalid status transition")
	ErrDuplicateSlug     = errors.New("duplicate slug")
)

// EventType represents the structure of an event (binary or multi-outcome).
type EventType int8

// EventType values.
const (
	EventTypeBinary       EventType = 0
	EventTypeMultiOutcome EventType = 1
)

func (t EventType) String() string {
	switch t {
	case EventTypeBinary:
		return "BINARY"
	case EventTypeMultiOutcome:
		return "MULTI_OUTCOME"
	default:
		return "UNKNOWN"
	}
}

// IsValid returns true if the event type is a known value.
func (t EventType) IsValid() bool {
	return t == EventTypeBinary || t == EventTypeMultiOutcome
}

// Status represents the lifecycle state of an event or market.
type Status int8

// Status values.
const (
	StatusActive   Status = 0
	StatusPaused   Status = 1
	StatusResolved Status = 2
	StatusVoided   Status = 3
)

func (s Status) String() string {
	switch s {
	case StatusActive:
		return "ACTIVE"
	case StatusPaused:
		return "PAUSED"
	case StatusResolved:
		return "RESOLVED"
	case StatusVoided:
		return "VOIDED"
	default:
		return "UNKNOWN"
	}
}

// IsValid returns true if the status is a known value.
func (s Status) IsValid() bool {
	return s >= StatusActive && s <= StatusVoided
}

// Outcome represents the resolved outcome of a market.
type Outcome int8

// Outcome values.
const (
	OutcomeYes Outcome = 0
	OutcomeNo  Outcome = 1
)

func (o Outcome) String() string {
	switch o {
	case OutcomeYes:
		return "YES"
	case OutcomeNo:
		return "NO"
	default:
		return "UNKNOWN"
	}
}

// IsValid returns true if the outcome is a known value.
func (o Outcome) IsValid() bool {
	return o == OutcomeYes || o == OutcomeNo
}

// ValidTransition returns true if moving from one Status to another
// is allowed.
//
// Allowed transitions:
//
//	active  → paused, resolved, voided
//	paused  → active
//	resolved → (none — terminal)
//	voided   → (none — terminal)
func ValidTransition(from, to Status) bool {
	switch from {
	case to:
		return false
	case StatusActive:
		if to == StatusPaused || to == StatusResolved || to == StatusVoided {
			return true
		}
	case StatusPaused:
		if to == StatusActive {
			return true
		}
	case StatusResolved, StatusVoided:
		return false
	}
	return false
}

// Category represents a grouping for events (e.g., "Sports", "Politics").
type Category struct {
	ID   string // UUID, generated by database.
	Name string
	Slug string // URL-friendly unique identifier.
}

// Event represents a top-level prediction event that may contain one or more
// markets. For example, "2024 US Presidential Election" with markets for each
// candidate.
type Event struct {
	ID                string // UUID, generated by database.
	Slug              string // URL-friendly unique identifier.
	Title             string
	Description       string
	CategoryID        *string // Nullable FK to categories.
	EventType         EventType
	ResolutionConfig  json.RawMessage // JSONB — always {} for manual resolution.
	Status            Status
	EndDate           time.Time
	Featured          bool
	FeaturedSortOrder int16
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// Market represents a single binary YES/NO prediction market.
// A market may belong to an event (multi-outcome) or be standalone (event_id null).
// All monetary amounts are in integer cents (1 = $0.01).
type Market struct {
	ID              string  // UUID, generated by database.
	Slug            string  // URL-friendly unique identifier.
	EventID         *string // Nullable FK to events; null for standalone markets.
	Question        string  // The prediction question.
	OutcomeYesLabel string  // Display label for YES outcome (default "Yes").
	OutcomeNoLabel  string  // Display label for NO outcome (default "No").
	TokenIDYes      string  // Conditional token ID for YES outcome.
	TokenIDNo       string  // Conditional token ID for NO outcome.
	ConditionID     string  // CTF condition ID.
	Status          Status
	Outcome         *Outcome // Null until resolved.
	PriceYes        int64    // Current YES price in cents (1-99).
	PriceNo         int64    // Current NO price in cents (1-99).
	Volume          int64    // Total traded volume in cents.
	OpenInterest    int64    // Current open interest in cents.
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
