// Package affiliate defines the domain types for the referral and affiliate
// earnings system in the prediction market platform service.
package affiliate

import (
	"errors"
	"time"
)

// Sentinel errors for the affiliate domain.
var (
	ErrNotFound          = errors.New("not found")
	ErrDuplicateReferral = errors.New("duplicate referral")
	ErrSelfReferral      = errors.New("self referral")
	ErrCircularReferral  = errors.New("circular referral")
	ErrDuplicateEarning  = errors.New("duplicate earning")
	ErrInvalidReferral   = errors.New("invalid referral")
	ErrInvalidEarning    = errors.New("invalid earning")
)

// Referral represents a referrer-referred relationship between two users.
type Referral struct {
	ReferrerAddress string    `db:"referrer_address"` // Ethereum address of the referrer.
	ReferredAddress string    `db:"referred_address"` // Ethereum address of the referred user.
	CreatedAt       time.Time `db:"created_at"`
}

// Earning represents a single earning event from a referred user's trade.
// All monetary amounts are in integer cents (1 = $0.01).
type Earning struct {
	ID              string    `db:"id"`               // UUID, generated by database.
	ReferrerAddress string    `db:"referrer_address"` // Ethereum address of the earning referrer.
	TradeID         string    `db:"trade_id"`         // FK to trades; idempotency key.
	FeeAmount       int64     `db:"fee_amount"`       // Total fee from the trade, in cents.
	ReferrerCut     int64     `db:"referrer_cut"`     // Portion of fee credited to referrer, in cents.
	CreatedAt       time.Time `db:"created_at"`
}

// ClaimableBalance represents a referrer's aggregate earnings.
// All monetary amounts are in integer cents (1 = $0.01).
type ClaimableBalance struct {
	ReferrerAddress string
	TotalEarned     int64 // Sum of all referrer_cut values.
	// Claimable is the portion of TotalEarned that has not yet been
	// withdrawn. Currently identical to TotalEarned because the
	// claims/withdrawal ledger does not exist yet — the deduction of
	// already-withdrawn amounts will land with that feature.
	Claimable int64
}
